"""마이그레이션과 모델이 어긋났는지 CI가 잡는다.

conftest는 속도 때문에 Base.metadata.create_all로 테이블을 판다(함수 단위 fixture라
매 테스트 마이그레이션 재생은 너무 비싸다). 그러면 "모델은 고쳤는데 마이그레이션을
안 만든" 사고를 아무도 못 잡는다 — 테스트는 다 통과하고 배포된 DB만 조용히 뒤처진다.

그 구멍을 이 파일 하나가 막는다. 빈 DB에 마이그레이션만으로 스키마를 세운 뒤,
그 결과가 모델과 일치하는지 alembic에게 직접 묻는다 (ADR-0007).
"""

import asyncio
from pathlib import Path

import pytest
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from tests.conftest import ADMIN_DB_URL, DB_URL

MIGRATION_DB_NAME = "travelops_migrations"
MIGRATION_DB_URL = DB_URL.set(database=MIGRATION_DB_NAME)
ALEMBIC_INI = Path(__file__).resolve().parent.parent / "alembic.ini"


async def _recreate_migration_database() -> None:
    """매번 완전히 빈 DB에서 시작한다 — 이전 실행의 잔재가 있으면 검사가 무의미하다."""
    engine = create_async_engine(ADMIN_DB_URL, isolation_level="AUTOCOMMIT")
    try:
        async with engine.connect() as conn:
            # 식별자는 바인딩이 안 된다. MIGRATION_DB_NAME은 이 파일의 상수라 주입 경로가 없다.
            # FORCE는 남아 있는 연결을 끊는다 (PostgreSQL 13+)
            await conn.execute(
                text(f'DROP DATABASE IF EXISTS "{MIGRATION_DB_NAME}" WITH (FORCE)')
            )
            await conn.execute(text(f'CREATE DATABASE "{MIGRATION_DB_NAME}"'))
    finally:
        await engine.dispose()


def test_migrations_produce_the_models_schema() -> None:
    """동기 테스트다.

    alembic의 env.py가 내부에서 asyncio.run을 돌기 때문에, 이미 실행 중인 이벤트 루프
    안에서 부르면 죽는다. pytest-asyncio auto 모드는 async def만 감싸므로 여기서는
    루프가 없다.
    """
    asyncio.run(_recreate_migration_database())

    config = Config(str(ALEMBIC_INI))
    # ini의 sqlalchemy.url이 아니라 attributes로 넘긴다 — env.py의 get_url()이 이 값을 먼저 본다.
    # ini 경로는 configparser 보간을 거쳐서 비밀번호에 %가 있으면 조용히 깨진다
    # str(URL)은 비밀번호를 ***로 가린다. 그대로 넘기면 인증에서 죽는다
    config.attributes["db_url"] = MIGRATION_DB_URL.render_as_string(hide_password=False)

    command.upgrade(config, "head")

    try:
        # 마이그레이션이 만든 스키마와 현재 모델의 차이를 alembic이 직접 계산한다.
        # 차이가 있으면 AutogenerateDiffsDetected
        command.check(config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "모델과 마이그레이션이 어긋났다. "
            "`alembic revision --autogenerate -m \"...\"`로 새 리비전을 만들어라.\n"
            f"{exc}"
        )
